server:
  ssl:
    key-store: classpath:keystore/${spring.profiles.active}/keystore.jks
    key-store-password: =az3xeches?ejuBr
    key-password: yakeJ+ChuF2reswA
eureka:
  client:
    service-url:
      defaultZone: http://eureka:7rupuwevUsPe@${eureka.backup.zone:localhost}:8100/eureka/
logging:
  path: ./log
  level:
    com.qy: INFO
    root: INFO