server:
  ssl:
    key-store: classpath:keystore/${spring.profiles.active}/keystore.jks
    key-store-password: testProd
    key-password: 8rU@rAPuzaFa
eureka:
  client:
    service-url:
      defaultZone: https://eureka:pass_123@${eureka.backup.zone:localhost}:8100/eureka/
logging:
  path: ./log
  level:
    com.qy: INFO
    root: INFO