spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
server:
  port: 9999
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}

zuul:
  add-proxy-headers: true
  host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 60000
  routes:
    business:
      stripPrefix: true
      path: /test/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: demo-role-authority
    link:
      stripPrefix: true
      path: /link/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: customer_link
    zl:
      stripPrefix: true
      path: /lp/zl/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: insurance-lp-zl
    zp:
      stripPrefix: true
      path: /lp/zp/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: insurance-lp-zp
    ls:
      stripPrefix: true
      path: /lp/ls/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: insurance-lp-ls
    hb:
      stripPrefix: true
      path: /aus/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: insurance-hb
    hbsurvey:
      stripPrefix: false
      path: /survey/aus/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: hb-survey
    lpsurvey:
      stripPrefix: false
      path: /survey/claim/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: lp-survey
  filter:
    routes:
      jwt:
        enable: true
        order: 1
        type: pre
        paths:
          - /test/**
          - /link/**
          - /aus/**
          - /survey/**
        roles:
          - role_test
          - ROLE_TRUSTED_CLIENT
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 60000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
