server:
  ssl:
    key-store: classpath:keystore/keystore.jks
    key-store-password: password
    key-password: password
eureka:
  client:
    service-url:
      defaultZone: https://${security.user.name}:${security.user.password}@localhost:${server.port}/eureka/
security:
  user:
    name: eureka
    password: pass_123 #password should not contain chars like '@'
