server:
  ssl:
    key-store: classpath:keystore/${spring.profiles.active}/keystore.jks
    key-store-password: store123
    key-password: pass123
eureka:
  client:
    service-url:
      defaultZone: https://${security.user.name}:${security.user.password}@localhost:${server.port}/eureka/
security:
  user:
    name: eureka
    password: pass_123 #password should not contain chars like '@'
logging:
  path: ./log
  level:
    com.qy: INFO
    root: INFO