server:
  ssl:
    key-store: classpath:keystore/keystore.jks
    key-store-password: password
    key-password: password
eureka:
  client:
    service-url:
      defaultZone: https://eureka:pass_123@localhost:8100/eureka/
logging:
  path: ./log
  level:
    com.qy: INFO
    root: INFO
database:
  link:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6e3308v0u0og2eto.mysql.rds.aliyuncs.com:3306/link_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: qybx_dev
    password: dev@123456
    type: com.alibaba.druid.pool.DruidDataSource
          #数据库连接池配置
    max-active: 5
    min-idle: 1
    initial-size: 1
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    validation-query: select 1
    #每10分钟收集空闲连接，单位毫秒#
    time-between-eviction-runs-millis: 600000
    #连接的最大空闲时间，单位毫秒，60分钟
    min-evictable-idle-time-millis: 3600000
    max-wait: 30000
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
  common:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-uf6e3308v0u0og2eto.mysql.rds.aliyuncs.com:3306/common_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: qybx_dev
      password: dev@123456
      type: com.alibaba.druid.pool.DruidDataSource
            #数据库连接池配置
      max-active: 5
      min-idle: 1
      initial-size: 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
      #每10分钟收集空闲连接，单位毫秒#
      time-between-eviction-runs-millis: 600000
      #连接的最大空闲时间，单位毫秒，60分钟
      min-evictable-idle-time-millis: 3600000
      max-wait: 30000
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)