spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
server:
  port: 9411
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
