logging:
  path: ./log
  level:
    com.qy: INFO
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://rm-m5e6886i1i43e4091.mysql.rds.aliyuncs.com:3306/common_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${username}
    password: ${password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#flyway:
#  locations: migration
#  baseline-on-migrate: true
#  validate-on-migrate: true
#  schemas: common_db
#  url: jdbc:mysql://rm-m5e6886i1i43e4091.mysql.rds.aliyuncs.com:3306/common_db
#  user: ${username}
#  password: ${password}