logging:
  path: ./log
  level:
    com.qy: INFO
    root: INFO
spring:
  datasource:
    url: jdbc:mysql://rm-uf6e3308v0u0og2eto.mysql.rds.aliyuncs.com:3306/common_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: qybx_dev_all
    password: QO0JFZCQX412T4koTZAB
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

flyway:
  locations: migration
  baseline-on-migrate: true
  validate-on-migrate: true
  schemas: common_db
  url: jdbc:mysql://rm-uf6e3308v0u0og2eto.mysql.rds.aliyuncs.com:3306/common_db
  user: qybx_dev_all
  password: QO0JFZCQX412T4koTZAB