server:
  ssl:
    key-store: classpath:keystore/${spring.profiles.active}/keystore.jks
    key-store-password: password
    key-password: password
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: https://eureka:pass_123@localhost:8100/eureka/
logging:
  path: ./log
  level:
    com.qy: INFO
    root: INFO