server:
  port: 8100
  ssl:
    key-store: classpath:keystore/keystore.jks
    key-store-password: password
    key-password: password
    clientAuth: want
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
eureka:
  server:
    response-cache-auto-expiration-in-seconds: 120
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
security:
  basic:
    enabled: true